<a href="https://colab.research.google.com/github/MuhammadSafeer786/My-PyTorch-Journey/blob/main/01_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Recources :

1- Github https://github.com/mrdbourke/pytorch-deep-learning

2- Book https://learnpytorch.io

3- Pytorch https://pytorch.org

4- Pytorch Forum

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors

### Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector[0]

tensor(7)

In [ ]:
Matrix = torch.tensor([[7,8],[9,7]])
Matrix

tensor([[7, 8],
        [9, 7]])

In [ ]:
Matrix[1]

tensor([9, 7])

In [ ]:
Tensor = torch.tensor([[[2,4,5],[4,9,6],[8,5,2]]])

**.size .shape .ndim** but **.item** is only apllicable on scalar

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

### Random Tensor
Why random tensors?

`Networks typicaly start with random numbers`

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9853, 0.5518, 0.2851, 0.2703],
        [0.9967, 0.0515, 0.1506, 0.8907],
        [0.8885, 0.8394, 0.9241, 0.2023]])

In [ ]:
random_tensor.ndim

2

In [ ]:
rand_img_tensor = torch.rand(size=(3,224,224))

In [ ]:
rand_img_tensor

tensor([[[0.0399, 0.7564, 0.5675,  ..., 0.2124, 0.1741, 0.7018],
         [0.9652, 0.7592, 0.0181,  ..., 0.0799, 0.5636, 0.4717],
         [0.0568, 0.0036, 0.8697,  ..., 0.0731, 0.8701, 0.0312],
         ...,
         [0.5398, 0.4667, 0.8213,  ..., 0.9600, 0.1229, 0.0709],
         [0.3514, 0.1536, 0.3899,  ..., 0.4814, 0.4631, 0.3654],
         [0.2692, 0.0709, 0.0490,  ..., 0.5650, 0.0392, 0.5347]],

        [[0.2491, 0.2184, 0.3644,  ..., 0.4886, 0.6168, 0.0608],
         [0.6774, 0.2352, 0.6268,  ..., 0.8725, 0.6683, 0.9347],
         [0.1754, 0.9543, 0.6169,  ..., 0.5414, 0.9047, 0.7738],
         ...,
         [0.1684, 0.9319, 0.8280,  ..., 0.7411, 0.0545, 0.9959],
         [0.0802, 0.3124, 0.7700,  ..., 0.9837, 0.6971, 0.5867],
         [0.7249, 0.6567, 0.3212,  ..., 0.6790, 0.2179, 0.6056]],

        [[0.0152, 0.5913, 0.4462,  ..., 0.1254, 0.0368, 0.5260],
         [0.1557, 0.3312, 0.6894,  ..., 0.6812, 0.9051, 0.8746],
         [0.6342, 0.0353, 0.5798,  ..., 0.1244, 0.5327, 0.

In [ ]:
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.zeros_like(random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Data Types in Tensors

In [ ]:
temp_tensor = torch.tensor([3.0,6.0,9.0],
                           dtype= torch.bfloat16,
                           device= 'cpu',
                           requires_grad= False) #track gradients

In [ ]:
temp_tensor.dtype

torch.bfloat16

In [ ]:
tensor32 = temp_tensor.type(torch.float32) # explicit type casting

In [ ]:
result1 = temp_tensor*tensor32
result2 = temp_tensor+tensor32
result3 = temp_tensor-tensor32
result4 = temp_tensor/tensor32
print(result1,result2,result3,result4)

tensor([ 9., 36., 81.]) tensor([ 6., 12., 18.]) tensor([0., 0., 0.]) tensor([1., 1., 1.])


In [ ]:
result1.dtype

torch.float32

In [ ]:
torch.matmul(temp_tensor.type(torch.float32), tensor32) # keep in mind the dimenstions of input e.g. Use Transpose when necessary.

tensor(126.)