<a href="https://colab.research.google.com/github/MuhammadSafeer786/My-PyTorch-Journey/blob/main/01_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Recources :

1- Github https://github.com/mrdbourke/pytorch-deep-learning

2- Book https://learnpytorch.io

3- Pytorch https://pytorch.org

4- Pytorch Forum

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors

### Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
vector[0]

tensor(7)

In [10]:
Matrix = torch.tensor([[7,8],[9,7]])
Matrix

tensor([[7, 8],
        [9, 7]])

In [11]:
Matrix[1]

tensor([9, 7])

In [12]:
Tensor = torch.tensor([[[2,4,5],[4,9,6],[8,5,2]]])

**.size .shape .ndim** but **.item** is only apllicable on scalar

In [13]:
Tensor.ndim

3

In [14]:
Tensor.shape

torch.Size([1, 3, 3])

### Random Tensor
Why random tensors?

`Networks typicaly start with random numbers`

In [15]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1101, 0.1773, 0.1838, 0.7896],
        [0.1232, 0.5202, 0.9041, 0.7492],
        [0.0347, 0.2311, 0.9075, 0.3127]])

In [16]:
random_tensor.ndim

2

In [17]:
rand_img_tensor = torch.rand(size=(3,224,224))

In [18]:
rand_img_tensor

tensor([[[0.9684, 0.3501, 0.6092,  ..., 0.3384, 0.3309, 0.6764],
         [0.7190, 0.3445, 0.3718,  ..., 0.6720, 0.2168, 0.6217],
         [0.3436, 0.3250, 0.9133,  ..., 0.8235, 0.7414, 0.3870],
         ...,
         [0.7436, 0.6702, 0.9351,  ..., 0.6395, 0.0437, 0.0563],
         [0.1590, 0.0647, 0.5421,  ..., 0.5960, 0.9424, 0.7870],
         [0.7099, 0.3570, 0.9586,  ..., 0.1476, 0.8113, 0.1031]],

        [[0.2040, 0.3171, 0.5274,  ..., 0.2698, 0.1328, 0.4596],
         [0.1847, 0.8716, 0.1719,  ..., 0.6645, 0.4968, 0.4076],
         [0.5140, 0.8372, 0.1952,  ..., 0.3541, 0.7887, 0.4561],
         ...,
         [0.9258, 0.2500, 0.3930,  ..., 0.9909, 0.5420, 0.9464],
         [0.3005, 0.8941, 0.6267,  ..., 0.4244, 0.8088, 0.9812],
         [0.2547, 0.8663, 0.3085,  ..., 0.6550, 0.5648, 0.4048]],

        [[0.5081, 0.4087, 0.9988,  ..., 0.5444, 0.1797, 0.9981],
         [0.1795, 0.6414, 0.5574,  ..., 0.2074, 0.6956, 0.7745],
         [0.0034, 0.5362, 0.1302,  ..., 0.1162, 0.2998, 0.

In [19]:
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.zeros_like(random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Data Types in Tensors

In [25]:
temp_tensor = torch.tensor([3.0,6.0,9.0],
                           dtype= torch.bfloat16,
                           device= 'cpu',
                           requires_grad= False) #track gradients

In [26]:
temp_tensor.dtype

torch.bfloat16

In [27]:
tensor32 = temp_tensor.type(torch.float32) # explicit type casting

In [28]:
result1 = temp_tensor*tensor32
result2 = temp_tensor+tensor32
result3 = temp_tensor-tensor32
result4 = temp_tensor/tensor32
print(result1,result2,result3,result4)

tensor([ 9., 36., 81.]) tensor([ 6., 12., 18.]) tensor([0., 0., 0.]) tensor([1., 1., 1.])


In [29]:
result1.dtype

torch.float32

In [30]:
torch.matmul(temp_tensor.type(torch.float32), tensor32) # keep in mind the dimenstions of input e.g. Use Transpose when necessary.

tensor(126.)

In [31]:
tensor = torch.tensor([1, 2, 3, 4, 5])
tensor_min = torch.min(tensor)
tensor_max = torch.max(tensor)
tensor_mean = torch.mean(tensor.float())  # Mean requires float input
tensor_sum = torch.sum(tensor)
print(f"Mean value: {tensor_mean}")
print(f"Min value: {tensor_min}")
print(f"Max value: {tensor_max}")
print(f"Sum value: {tensor_sum}")

Mean value: 3.0
Min value: 1
Max value: 5
Sum value: 15


### Reshaping, Stacking, Squeezing and Unsqueezing Tensors
* **Reshaping** reshapes and keeps the total number of elements same
* **View** of a tensor is a tensor of certain shape but keeps the same memory as the orignal tensor.
* **Stacking** combines tensors
* **Squeeze** and **Unsqueeze** removes all `1` dimensions and adds a `1` dimension to the ternsor respectively
* **Permute** Return a view of input with dimensions swapped (permuted) in a certain way

In [32]:
tensor = torch.arange(1.,11.)
tensor, tensor.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [33]:
# It cannot reshape to dimensions whose multiple is not equal to total number of elements i.e. 2 x 5 = 10
reshaped = tensor.reshape(2,5) # try (10,1)
reshaped, reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [34]:
z = tensor.view(10,1)
z, z.shape    # z and tensor share same memory, changes will be reflected

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [35]:
stacked = torch.stack([tensor,tensor,tensor,tensor],dim=1) # dim = 1 is torch.hstack and dim = 0 is torch.vstack
stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [42]:
x = torch.zeros(2, 1, 2, 1, 2)
x.shape

torch.Size([2, 1, 2, 1, 2])

In [38]:
y = torch.squeeze(x,dim=3) # removes '1' dimensions in the specified dims i.e. dim=3 would remove 1 in the 3rd dim if the orignal shape has 1 in that place : (3,28,28,1) -> (3,28,28)
y.size()

torch.Size([2, 1, 2, 2])

In [41]:
y = torch.unsqueeze(x,dim=3) # adds '1' dimensions in the specified dims i.e. dim=3 would add 1 in the 3rd dim if the orignal shape has 1 in that place :
y.shape

torch.Size([2, 1, 2, 1, 1, 2])

In [45]:
# mostly used with images
img = torch.rand(size=(224,224,3))
y = torch.permute(img, (2,0,1)) # returns a **view** of swapped shape i.e. its aurgument is actually we telling it to place which dimension in which place. see the output for better understanding
y.shape

torch.Size([3, 224, 224])

# Indexing Data
Important Note if shape is (1,3,3) then biggest index could only be [0][2][2], notice that we cannot index bigger or equal to dimensions

In [46]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [47]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
x[0][0]

tensor([1, 2, 3])

In [49]:
x[0,0] # similar to above !

tensor([1, 2, 3])

In [50]:
x[0][0][0]

tensor(1)

In [51]:
x[:,:,1]  # : means all of a target dimension

tensor([[2, 5, 8]])

In [52]:
x[0,:,1] # notice one less [] bracket in the output

tensor([2, 5, 8])

#Numpy & pytorch

In [54]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) # default of numpy as float64 while default of pytorch's tensor is float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))